version: '3.8'

services:
  # PHP service for Laravel application
  php:
    image: php:8.3-cli-bookworm
    volumes:
      # Mount package source so it can be installed via Composer path repo
      - ../..:/package
      # Persistent demo Laravel application
      - ./demo-app:/var/www/html
    working_dir: /var/www/html
    environment:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
      CACHE_DRIVER: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
    ports:
      - "8000:8000"
    command: >
      bash -c "
        set -e
        # Install system & PHP extensions
        apt-get update && apt-get install -y git unzip zip libzip-dev libicu-dev libsqlite3-dev &&
        docker-php-ext-install pdo pdo_sqlite zip intl &&
        # Install Composer
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        # If the demo app does not yet exist, create and configure it
        if [ ! -f artisan ]; then
          echo 'Creating demo Laravel application…' &&
          composer create-project --quiet laravel/laravel . &&
          # Configure local path repository for Stitch Wizard
          composer config --absolute --working-dir=. repositories.stitch-wizard path /package &&
          composer require --no-interaction dalersingh/stitch-wizard:@dev &&
          # Publish & migrate
          php artisan vendor:publish --provider=\"Dalersingh\\StitchWizard\\StitchWizardServiceProvider\" --force &&
          php artisan migrate --force
        fi &&
        php artisan serve --host=0.0.0.0 --port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - e2e-network

  # Playwright service for E2E tests
  playwright:
    build:
      context: ../..
      dockerfile: docker/e2e-tests/Dockerfile
    volumes:
      - ../..:/app
      - ./test-results:/app/test-results
    working_dir: /app
    environment:
      PLAYWRIGHT_BASE_URL: http://php:8000
      CI: "true"
      NODE_ENV: test
    depends_on:
      php:
        condition: service_healthy
    command: ["npx", "playwright", "test", "e2e/tests"]
    networks:
      - e2e-network

networks:
  e2e-network:
    driver: bridge
